//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyPhoto.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyPhoto.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alubms.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed!.
        /// </summary>
        public static string downFaild {
            get {
                return ResourceManager.GetString("downFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Album name:.
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Albums.
        /// </summary>
        public static string GotoAlbums {
            get {
                return ResourceManager.GetString("GotoAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete album .
        /// </summary>
        public static string msgDelAlbum {
            get {
                return ResourceManager.GetString("msgDelAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Album.
        /// </summary>
        public static string msgDelAlbumTitel {
            get {
                return ResourceManager.GetString("msgDelAlbumTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletion failed!.
        /// </summary>
        public static string msgDelFailed {
            get {
                return ResourceManager.GetString("msgDelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete .
        /// </summary>
        public static string msgDelPic {
            get {
                return ResourceManager.GetString("msgDelPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Photo.
        /// </summary>
        public static string msgDelPicTitle {
            get {
                return ResourceManager.GetString("msgDelPicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload captured photo to Skydrive?.
        /// </summary>
        public static string msgUp {
            get {
                return ResourceManager.GetString("msgUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string msgUpTitle {
            get {
                return ResourceManager.GetString("msgUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New album failed!.
        /// </summary>
        public static string newAlbumFaild {
            get {
                return ResourceManager.GetString("newAlbumFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new album.
        /// </summary>
        public static string NewAlubum {
            get {
                return ResourceManager.GetString("NewAlubum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading albums.
        /// </summary>
        public static string progMsgDownAlbum {
            get {
                return ResourceManager.GetString("progMsgDownAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading album photos.
        /// </summary>
        public static string progMsgDownAlumPic {
            get {
                return ResourceManager.GetString("progMsgDownAlumPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading photos.
        /// </summary>
        public static string progMsgDownPic {
            get {
                return ResourceManager.GetString("progMsgDownPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading photo.
        /// </summary>
        public static string progMsgUpPic {
            get {
                return ResourceManager.GetString("progMsgUpPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out .
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed!.
        /// </summary>
        public static string upFaild {
            get {
                return ResourceManager.GetString("upFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
